# A Python program that will print out a random joke and punchline from a selection
# Written by Austin Bricker, 2017

joke_list = {"What does a grape say when it's stepped on?":"Nothing, it just lets out a little wine.",
            "What did the buffalo say to its child when it left?":"Bison. (I bet you herd that one before!)",
            "How many tickles does it take to make an octopus laugh?":"Tentacles.",
            "What weighs 6 ounces, sits in a tree, and is very dangerous?":"A sparrow with a machine gun.",
            "What happens when you tell an egg a joke?":"It cracks up.",
            "Why was the big cat disqualified from the race?":"Because it was a cheetah!",
            "What side of a fish has the most scales?":"The outside.",
            "What do you call a cow lying on the floor?":"Ground beef",
            "Why can't you hear a pterodactyl go to the bathroom?":"The P is silent.",
            "What do you call a fly without wings?":"A walk.",
            "How do you make a hankie dance?":"You put a little boogie in it.",
            "Have you ever heard of the music group called Cellophane?":"They mostly wrap.",
            "What kinds of magic do cows believe in?":"MooDoo",
            "Why does it take longer to get from first to second base than from second to third?":"Because there's a shortstop in between.",
            "Do you know where you can get chicken broth in bulk?":"The stock market.",
            "What did the ocean say to the shore?":"Nothing, it just waved.",
            "What do you call a dinosaur with an extensive vocabulary?":"A thesaurus",
            "What does a clock do when it's hungry?":"It goes back four seconds.",
            "Why do I need my glasses to do math?":"For di-vision",
            "What kind of music do wind turbines like?":"They're huge metal fans.",
            "What do you call a deer with no eyes?":"No eye deer",
            "What's the difference between a lobster with breast implants and a dirty bus stop?":"One's a crusty bus station, the other's a busty crustacean.",
            "How do you find Will Smith in the snow?":"Look for the fresh prints.",
            "Two peanuts walk into a bar. One was a salted.":"Same thing happened with two pretzels in an alley.",
            "What time did the man go to the dentist?":"Tooth hurt-y",
            "Why did the Clydesdale give the pony a glass of water?":"Because he was a little horse.",
            "How do you make holy water?":"You boil the hell out of it.",
            "What is Beethoven's favorite fruit?":"A ba-*na-na-na*",
            "What is the difference between a hippo and a zippo?":"One is really heavy, the other is a little lighter.",
            "Did you know that you can't run through a campsite?":"You can only ran, because it's past tents.",
            "What happened to the cow that jumped over the barbed wire fence?":"Udder destruction.",
            "Why can't a bicycle stand on its own?":"It's two tired.",
            "Did you hear about the new restaurant on the moon?":"The food is great, but there's no atmosphere.",
            "Why did the octopus beat the shark in a fight?":"Because it was well armed.",
            "What did the fish say when it swam into a wall?":"Dam!",
            "Why does a chicken coop only have two doors?":"If it had four doors it would be a chicken sedan!",
            "Why don't seagulls fly over the bay?":"Because then they would be bay-gulls!",
            "What did the late tomato say to the early tomato?":"I'll ketchup.",
            "What did 0 say to 8?":"Nice belt.",
            "Where does Napoleon keep his armies?":"In his sleevies.",
            "Why did the scarecrow win an award?":"Because he was outstanding in his field.",
            "Why do SCUBA divers fall backwards into the water?":"Because if they fell forwards they'd still be in the boat.",
            "What's the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle?":"Attire.",
            "What do you call a fake noodle?":"An impasta.",
            "What does a mermaid wear to math class?":"An algae-bra.",
            "Why don't lobsters give to charity?":"Because they're shellfish.",
            "Why did the girl smear peanut butter on the road?":"To go with the traffic jam.",
            "Why didn't the skeleton cross the road?":"Because he had no guts.",
            "What do you call a fish with no eyes?":"A fsh.",
            "What's orange and sounds like a parrot?":"A carrot.",
            "Did you hear about the kidnapping at school?":"It's okay, he woke up.",
            "What's the best thing about elevator jokes?":"They work on so many levels.",
            "How do you make antifreeze?":"Steal her blanket.",
            "What's the difference between beer nuts and deer nuts?":"Beer nuts are about 49 cents, and deer nuts are just under a buck.",
            "What kind of luggage does a vulture take on a plane?":"Carrion.",
            "Want to hear a word I just made up?":"Plagiarism.",
            "What's the definition of a will?":"It's a dead giveaway.",
            "Why is the vampire a vegan?":"A steak would kill him.",
            "What do you call an alligator wearing a vest?":"An investigator.",
            "Who was the roundest member of King Arthur's Court?":"Circumference"
            }

def joke():
    return joke_list
